### ISSUE TITLE
Make important classes serializable

### ISSUE THREAD

**Issue by kwin** [adobe/aio-lib-java-cloudmanager#8]
To ease reuse this client in Jenkins Pipelines it is important that they implement serializable (further details in https://www.jenkins.io/blog/2017/02/01/pipeline-scalability-best-practice/). This is especially important for https://github.com/adobe/aio-lib-java-cloudmanager/blob/main/src/main/java/io/adobe/cloudmanager/impl/CloudManagerApiImpl.java.

**Comment by bstopp** [comment]
I will grant that I do need to add `Serializable` to the classes in `io.adobe.cloudmanager`. But I don't think that the Cloud Manager API should be included in that list.

This isn't something that should be passed between steps of the pipeline, or across primary/agents for execution. Steps can create their API instances as necessary since the _Token_ is serializable.

**Comment by kwin** [comment]
Ok, I see, then we are left with only making `AdobeClientCredentials` serializable. That should be sufficient.
